//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pmkb.Bot.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pmkb.Bot.Resources.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        internal static string DisclaimerTitle {
            get {
                return ResourceManager.GetString("DisclaimerTitle", resourceCulture);
            }
        }
        
        internal static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        internal static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        internal static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        internal static string GettingStartedText {
            get {
                return ResourceManager.GetString("GettingStartedText", resourceCulture);
            }
        }
        
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        internal static string ExamplePrompt1 {
            get {
                return ResourceManager.GetString("ExamplePrompt1", resourceCulture);
            }
        }
        
        internal static string ExamplePrompt2 {
            get {
                return ResourceManager.GetString("ExamplePrompt2", resourceCulture);
            }
        }
        
        internal static string ExamplePrompt3 {
            get {
                return ResourceManager.GetString("ExamplePrompt3", resourceCulture);
            }
        }
        
        internal static string ExamplePrompt4 {
            get {
                return ResourceManager.GetString("ExamplePrompt4", resourceCulture);
            }
        }
        
        internal static string WhoAmI1 {
            get {
                return ResourceManager.GetString("WhoAmI1", resourceCulture);
            }
        }
        
        internal static string WhoAmI2 {
            get {
                return ResourceManager.GetString("WhoAmI2", resourceCulture);
            }
        }
        
        internal static string Genes {
            get {
                return ResourceManager.GetString("Genes", resourceCulture);
            }
        }
        
        internal static string IAmThePmkbBot {
            get {
                return ResourceManager.GetString("IAmThePmkbBot", resourceCulture);
            }
        }
        
        internal static string GetGenesTitle {
            get {
                return ResourceManager.GetString("GetGenesTitle", resourceCulture);
            }
        }
        
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        internal static string HelloPrompt1 {
            get {
                return ResourceManager.GetString("HelloPrompt1", resourceCulture);
            }
        }
        
        internal static string HelloPrompt2 {
            get {
                return ResourceManager.GetString("HelloPrompt2", resourceCulture);
            }
        }
        
        internal static string HelloPrompt3 {
            get {
                return ResourceManager.GetString("HelloPrompt3", resourceCulture);
            }
        }
        
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        internal static string Gene {
            get {
                return ResourceManager.GetString("Gene", resourceCulture);
            }
        }
        
        internal static string Variants {
            get {
                return ResourceManager.GetString("Variants", resourceCulture);
            }
        }
        
        internal static string TumorTypes {
            get {
                return ResourceManager.GetString("TumorTypes", resourceCulture);
            }
        }
        
        internal static string PrimarySites {
            get {
                return ResourceManager.GetString("PrimarySites", resourceCulture);
            }
        }
        
        internal static string Interpretationfor {
            get {
                return ResourceManager.GetString("Interpretationfor", resourceCulture);
            }
        }
        
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        internal static string InterpretationsAssociatedWith {
            get {
                return ResourceManager.GetString("InterpretationsAssociatedWith", resourceCulture);
            }
        }
        
        internal static string Interpretation {
            get {
                return ResourceManager.GetString("Interpretation", resourceCulture);
            }
        }
        
        internal static string ThereAre {
            get {
                return ResourceManager.GetString("ThereAre", resourceCulture);
            }
        }
        
        internal static string InterpretationsInTotal {
            get {
                return ResourceManager.GetString("InterpretationsInTotal", resourceCulture);
            }
        }
    }
}
